### ISSUE TITLE
So there is going to be an error when HA updates to python 3.10..

### ISSUE THREAD

**Issue by Wibias** [Wibias/hass-variables#10]
Just a headups for me or if anyone already had that problem that I need to fix this.

```
/config/custom_components/variable/__init__.py:117: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  yield from asyncio.wait(tasks, loop=hass.loop)


/config/custom_components/variable/__init__.py:117: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
  yield from asyncio.wait(tasks, loop=hass.loop)
```

https://github.com/Wibias/hass-variables/blob/master/custom_components/variable/__init__.py#L117

**Comment by Wibias** [comment]
So this gonna have to do something with this.. Open for a PR..

https://docs.python.org/3/library/asyncio-task.html?highlight=wait#asyncio-example-wait-coroutine
https://docs.python.org/3/whatsnew/3.10.html#changes-in-the-python-api

**Comment by finity69x2** [comment]
you might be better off to post a question in the developers discord for HA than hoping someone knowledgeable sees this issue.

I am definitely not one of the knowledgeable enough ones but I would hate to see this integration break.
