### ISSUE TITLE
Example Usage - Play and Save TTS Messages + Message History

### ISSUE THREAD

**Issue by jazzyisj** [Wibias/hass-variables#14]
I've been using your integration in a kinda unique way so I thought I'd share it with you.
Feel free to mention it in your examples if you think it's interesting enough.

https://github.com/jazzyisj/save-tts-messages

**Comment by Wibias** [comment]
Interesting. Gonna look at that on the weekend when I finally got some time on my hand!

**Comment by Wibias** [comment]
Pretty interesting added it. Thanks for that!
