### ISSUE TITLE
Iot class: Local push?

### ISSUE THREAD

**Issue by Mariusthvdb** [Wibias/hass-variables#2]
HI,

noticed you updated the iot class, and indicate you are not sure it is correct. given https://www.home-assistant.io/blog/2016/02/12/classifying-the-internet-of-things/
wouldn't you feel it needs to be 'local push' ?

class 'calculated' doest exist, so it must be incorrect ;-)

**Comment by Wibias** [comment]
So the IOT-Class 'calculated' actually exists. For example this integration is in the iot class 'calculated' https://www.home-assistant.io/integrations/derivative/ Not sure where I read about it before but what ever. 
Wasn't sure what would fit the best. But I can make it local push for sure!
