### ISSUE TITLE
Integration not loading

### ISSUE THREAD

**Issue by craggus2000** [Wibias/hass-variables#21]
Hi,
I'm running latest version of HA, and downloaded and installed this custom integration via HACS, however it does not appear in the main integrations list to add. Subsequent custom integrations I have added do appear. I've restarted and refreshed, several times, and even left overnight, but it still does not appear.
Can you please assist?
Many thanks

**Comment by Fusion-Z** [comment]
Just chiming in here to say I'm also having the same issue. 
I've tried both through HACS and manually, but nothing showing up.

Home Assistant Repair shows....
"The automation "Automation Name" (automation.automation_name) has an action that calls an unknown service: variable.set_variable"

Home Assistant Logs show....
"Error executing script. Service not found for call_service at pos 1: Unable to find service variable.set_variable"

No other clues and would very much apperciate some assistance.
Cheers

**Comment by Wibias** [comment]
Hey.

There is nothing u have to add in the integrations list. It just works after you installed it over hacs.
