### ISSUE TITLE
unique_id - already working ?

### ISSUE THREAD

**Issue by frank-dusign** [Wibias/hass-variables#25]
Versions:
HA 2023.1.4
Variable 2.3.3

Hi,
thanks for the great work until now and in future.
I have seen that there is some work on the unique_id tag for the variable.
But adding the unique_id: tag in the configuration.yaml will end with an error (Invalid config for [variable]: [unique_id] is an invalid option for [variable].).
now the questions:
1. is unique_id already working in 2.3.3 ?
2. or am I doing something wrong ?
Here my definiton:
variable:
  kueche:
     restore: true
     value: 18
     unique_id: 2000001

**Comment by Wibias** [comment]
So I made it working. Documentation alias Readme really needs some work though to explain this custom component. But dont got time right now to almsot fully rewrite that.

https://github.com/Wibias/hass-variables/commit/ef001f2d44a315128b623979099a784806ea4543

**Comment by frank-dusign** [comment]
Sorry. 2.3.6 still same error message in HA. reviewing the code changes from 2.3.3 to 2.3.6. show the removal of all codes containing unique_id.
Really sure it is working in 2.3.6 ?

**Comment by Wibias** [comment]
View this. https://github.com/Wibias/hass-variables/issues/27

Unique id will not work with this component how it is right now.

If you know how to do it completly without interfering with the variable_id feel free to do a pull request. The old approach does not work.
