### ISSUE TITLE
With v.2.3.5 update some variable's attributes dissapered !

### ISSUE THREAD

**Issue by gribouk** [Wibias/hass-variables#26]
Dear All, after updating to v 2.3.5 I started getting missing attributes errors in the logs for my variables like below:

```
		Lights, main module PROCEDURES: Error executing script. Error rendering template for choose at pos 1: UndefinedError: 'homeassistant.util.read_only_dict.ReadOnlyDict object' has no attribute 'next_update'
```

Moreover, it is not enough to simply revert to v.2.3.3 since the error persists even after this. I have to restore the whole configuration before update to v.2.3.5 which means, that v2.3.5 eliminates some of my attributes for my variables on the first start up causing lots of problems.

With 2.3.3 everything works fine and it does find the attributes...

**Comment by Wibias** [comment]
So I reverted the change. Turns out that I forgot that there is already variable_id. Combined with unique_id that doesnt work very well.. Sorry for that. Pushing the old version out.

**Comment by pickonedev** [comment]
Thank you!!!

I don't know who need the unique_id...
I think that entity_id it is enough to use this addon. If someone whats to change the entity_id, just edit the yaml file and that's it, right?
