### ISSUE TITLE
Variable with MQTT value

### ISSUE THREAD

**Issue by pickonedev** [Wibias/hass-variables#3]
Hi!

There is any way in order to make a variable which listen to mqtt and get the value from a topic?

Thank you!

**Comment by pickonedev** [comment]
Nobody?! Any info?

**Comment by jazzyisj** [comment]
Why are you nut using a [template sensor ](https://www.home-assistant.io/integrations/template/)to do this?

**Comment by pickonedev** [comment]
> 
> 
> Why wouldn't you use a [template sensor ](https://www.home-assistant.io/integrations/template/)to do this?

Template sensor do not retain the value after HA restart, when use for MQTT. Variable retain the value, if you specify that
