### ISSUE TITLE
Config not working after Rename

### ISSUE THREAD

**Issue by RalfAlbers** [Wibias/hass-variables#4]
Hi,

after renaming from custom_components/variable to custom_components/variable_history the existing configuration is not longer working!

Also the doku is not reflecting this.

**Comment by ludeeus** [comment]
https://github.com/Wibias/hass-variables/issues/5#issuecomment-860174547

**Comment by Wibias** [comment]
https://github.com/Wibias/hass-variables/issues/5#issuecomment-860182411
