### ISSUE TITLE
Question: Added value over the HA helpers?

### ISSUE THREAD

**Issue by lenwar** [Wibias/hass-variables#44]
Hi,

First off, I don't want to bash or be disrespectful to the makers of this custom Integration. I just want to ask a question :)

I have been in the process of migrating my variable.* variables to native HA-helpers for a number of weeks now. Mostly because the helpers are configurable via the web interface. (taking my time, doing a few small things in between everything every now and then)

In the recent 3.x upgrade (which I didn't do, because a **lot** of my automations depend on the variable.xyz entities, and it would cost me too much time to change everything in one go). I was looking in to the new features of this Integration, but I really can't make out what the current added value over this integration is, over the native 'helpers' of HA.

So my question is:

What is the functional added value of this integration in comparison to the native HA-helpers? What can this integration do, that I can't do with the HA-helpers. (or at least make life a lot easier than to work with the HA-helpers)

**Comment by Snuffy2** [comment]
I think there are ~3.5 reasons:
1. **Probably the biggest one:** You can set and updates attributes to the entities in addition to just the values/states. The state has a max length of 255 characters while the attributes limit (for all attributes combined) is 16384 bytes and possibly longer if not stored in the recorder.
2.  Still in progress but a big reason for this change: the ability to set Device Class, State Class, Unit of Measurement in native ways that isn't just set in the Attributes and susceptible to being removed by future Attribute updates.
3. Similar to \# 2, you can create native entities with more classes that one is supported by the current helpers. First will be for the sensors, then binary_sensors. Future will be for other platforms.

(0.5). Based on initial feedback, there is a strong desire to keep the ability to create these via YAML. Currently in beta is the continued ability to create variable entities in YAML in addition to the option of creating and managing in the UI. Not sure the YAML based ones will have all of the options/features of the UI ones, but if we can get it working correctly, we will try to support both.
