### ISSUE TITLE
Fail to load integration variables after update to 2.1.2

### ISSUE THREAD

**Issue by gribouk** [Wibias/hass-variables#5]
Hello,

With the update to 2.1.2 I get error in config that integration variables is not found and none of my scripts work anymore...

What implicatons are there to use it now?

As I understand the domain name is changed, which imples it has to be changed all over my templates. Since I have maaaaaany of them using variables, can I actually question what was the motivation for such a drastic moove?

**Comment by ludeeus** [comment]
2.1.2 has a **major** breaking change
it changed from  `variable` to `variable_history`, release notes does not indicate this, README still uses the old `variable` domain.

To fix it change:

```
variable:
  ...
```
to: 
```
variable_history:
  ...
```

**Comment by gribouk** [comment]
> 2.1.2 has a **major** breaking change
> it changed from `variable` to `variable_history`, release notes does not indicate this, README still uses the old `variable` domain.
> 
> To fix it change:
> 
> ```
> variable:
>   ...
> ```
> 
> to:
> 
> ```
> variable_history:
>   ...
> ```

Yes, but do I have to ammend all of my templates as well since they all reference variable domain?

**Comment by ludeeus** [comment]
Yup <https://github.com/Wibias/hass-variables/blob/master/custom_components/variable_history/__init__.py#L127> :(

**Comment by gribouk** [comment]
> Yup https://github.com/Wibias/hass-variables/blob/master/custom_components/variable_history/__init__.py#L127, https://github.com/Wibias/hass-variables/blob/master/custom_components/variable_history/__init__.py#L17 :(

So, for those of you who run into problems:
1. replase variable - >variable_history in config.yaml
2. Using Notepad(or other editor) in your scripts.yaml and automations.yaml do replacements:
    2.1 variable. --> variable_history.
    2.2 states.variable --> states.variable_history

Is there any other pot4entially hazardous structure that can be met with domain variable that I've missed? Please share if you know.

And what was the reason for a domain change?

**Comment by ludeeus** [comment]
I don't know (to both questions) I don't use this integration myself.
Only @Wibias would know that.

**Comment by HelmutEsterer** [comment]
Hello,

at first I have to say - till now you did a great work! - Thank you!!!

But with last update and such a **big braking change** without a hint in
very big, big letters in your readme or releasenotes for breaking changes
I have to say it is unprofessional for me!
(I am angry.)

- Sorry, but this is my opinion an I think this behavior has no good effect for the whole project.

With best regards

Helmut

**Comment by Wibias** [comment]
Yea, I am sorry about that. I made that change since somewhere in the back of my head I thought there was a core integration named variable. I dont know if i dreamt of that, if it got removed or if i am mistaking.

Gonna reverse that change right now.
