### ISSUE TITLE
No file found 'custom_components/variable/manifest.json' Error

### ISSUE THREAD

**Issue by pickonedev** [Wibias/hass-variables#6]
Hi!

After the last update, I get 6-10 errors like this per day. I checked and the file exists. Any solution?

`<Integration Wibias/hass-variables> No file found 'custom_components/variable/manifest.json'
12:27:11 – (ERROR) HACS (custom integration) - message first occurred at 02:27:11 and shows up 9 times `

**Comment by Wibias** [comment]
Cant reproduce. Just "Uninstall - Restart - Install - Restart" the component. Should work after you did the steps.

**Comment by pickonedev** [comment]
Thank you! :-D
