### ISSUE TITLE
Custom Domains: Question

### ISSUE THREAD

**Issue by coaster3000** [Wibias/hass-variables#61]
So I noticed in the commit history of the project, there had been the ability to use custom Domains for variables and I know that there was a big change for 3.0 involving how variables will work moving forward (utilizing the platform API)

Is it still possible to use custom domains? I have been reading through the code and I haven't gotten too far into that at this time, but noticed that between the time the custom domains were implemented and the massive changes done for 3.0, there is a lot that changed which would effect custom domain handling.

I believe the feature was removed but as I had mentioned, I did not get that far in the code yet due to my work schedule.

If it was removed, Would having custom domain support still be within the scope of this project to be reimplemented?

**Comment by 50494554524F** [comment]
they should bring it back (have to test v3 btw) because, ie, i created variable.clipboard and it isn't nice :D to see sensor.clipboard...

**Comment by Snuffy2** [comment]
No v3 does not support custom domain names. Instead `Variables` is supporting more of the native functionality of the different, existing entity types. Otherwise, you can still do everything you used to in earlier versions, but all Variables defined by YAML will be `sensor.`
