### ISSUE TITLE
RuntimeWarning: coroutine 'ConfigEntries.async_reload' was never awaited

### ISSUE THREAD

**Issue by Snuffy2** [Wibias/hass-variables#65]
2023-06-17 21:55:32.981 WARNING (MainThread) [py.warnings] /config/custom_components/variable/__init__.py:224: RuntimeWarning: coroutine 'ConfigEntries.async_reload' was never awaited
  hass.config_entries.async_reload(entry_id)

**Comment by skynet01** [comment]
Happens to me as well

**Comment by Wibias** [comment]
Just change `hass.config_entries.async_reload(entry_id)` to `await hass.config_entries.async_reload(entry_id)` in 224 or nah? Error doesnt happen for me so I cant check it.

**Comment by Snuffy2** [comment]
> Just change `hass.config_entries.async_reload(entry_id)` to `await hass.config_entries.async_reload(entry_id)` in 224 or nah? Error doesnt happen for me so I cant check it.

No. That triggers a different error about awaiting itself or something like that. I've tried a couple of things, but haven't found the right combo to make HA happy.
