### ISSUE TITLE
Can you add switch method to binary sensor?

### ISSUE THREAD

**Issue by Bibyte** [Wibias/hass-variables#74]
I do not need to set true or false value to the binary_sensor, but need to call switch service, then binary_sensor if it is True - change to False. Or if it is False - cahnge to True.

**Comment by Snuffy2** [comment]
A variable.toggle_binary_sensor service could possibly be created. 

For now though, you can do this with an if-else in an automation, script or template.

**Comment by seanmccabe** [comment]
Can you not use

```
service: input_boolean.toggle
```
