### ISSUE TITLE
I need Increment and Decrement service for values 

### ISSUE THREAD

**Issue by Bibyte** [Wibias/hass-variables#75]
I need Increment and Decrement service for float (integer) values 

for example: if it 4  -call Increment service with step parametr = 1 will change value to 5. With step value 0.1 - change value to 4.1

**Comment by Snuffy2** [comment]
This is probably best done through an automation, script, or template using the variable.update_sensor service.

**Comment by seanmccabe** [comment]
I do this for incrementing

```
plays: "{{ 1 + state_attr(variable, 'plays')|int(1) }}"
```
