### ISSUE TITLE
How to use varialbe in automation? 

### ISSUE THREAD

**Issue by herbzhao** [Wibias/hass-variables#8]
I want to have an offset for my sunset elevation angle, here is what i do in the automation:
![image](https://user-images.githubusercontent.com/13511170/142026946-ffd06b01-5347-4a56-861b-ab9750547dec.png)

Here is what i have in the configuration.yaml
![image](https://user-images.githubusercontent.com/13511170/142026998-d5521d89-980d-4555-b1d5-8f09eb7c1581.png)

Am I missing something obvious here?

**Comment by Wibias** [comment]
Can you give me the yaml part of that top part. Not really familar with the ui automation thingy.
