### ISSUE TITLE
Adding Variables removes apostrophes

### ISSUE THREAD

**Issue by seanmccabe** [Wibias/hass-variables#84]
Had an interesting one when naming a variable "Wonderland's War".
Upon saving the apostrophe was removed, making it "Wonderlands War". This then broke a couple of my automations relying on the name.

The apostrophe was there when it was imported from yaml, but as I had to recreate it, upon doing this using the UI it apparently removes apostrophes (') from the variable name.

**Comment by Snuffy2** [comment]
It was the name and not the entity_id where the apostrophe disappeared, correct?
